### ISSUE TITLE
Implement Sub-Problems

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/odop#90] opened 2018-08-02 22:17 UTC
Design Parameter and State Variable Rows should be displayed or not depending on the value of IOCLASS.

See ideas for the View menu and related discussion of IOCLASS for Sub-Problems in menu.md. 

Per discussion, this feature should be part of the spring problem implementation.

**Comment by grumpyinca** [comment] 2018-08-26 12:42
See issue #170.

**Comment by 1fifoto** [comment] 2018-08-28 21:33
Duplicate of 170, closing

**Closed by 1fifoto** 2018-08-28 21:33 UTC
